const PLANETS={1:['Sun','Identity, leadership, vitality'],2:['Moon','Mind, emotions, sensitivity'],3:['Jupiter','Knowledge, learning, wisdom'],4:['Rahu','Energy, unconventional force'],5:['Mercury','Intelligence, communication, adaptability'],6:['Venus','Love, beauty, creativity, attraction'],7:['Ketu','Introspection, spirituality, detachment'],8:['Saturn','Service, discipline, patience, endurance'],9:['Mars','Action, courage, drive']};
const CHALDEAN={A:1,I:1,J:1,Q:1,Y:1,B:2,K:2,R:2,C:3,G:3,L:3,S:3,D:4,M:4,T:4,E:5,H:5,N:5,X:5,U:6,V:6,W:6,O:7,Z:7,F:8,P:8};
const PYTH={A:1,B:2,C:3,D:4,E:5,F:6,G:7,H:8,I:9,J:1,K:2,L:3,M:4,N:5,O:6,P:7,Q:8,R:9,S:1,T:2,U:3,V:4,W:5,X:6,Y:7,Z:8};
const FAV={1:[2,3,4,5],2:[1,3,7],3:[1,2,7,9],4:[1,5,6,8],5:[1,4,6,8,9],6:[4,5,7,8],7:[1,2,5,6,8],8:[1,4,5,6,7],9:[1,2,3,7]};
const CHAL={1:[6,7,8,9],2:[4,5,6,8],3:[4,5,6,8],4:[2,3,7,9],5:[2,3,7],6:[1,9],7:[3,4,9],8:[2,3,9],9:[4,5,6,8]};
const MEAN={1:'Creator, leader, independent',2:'Sensitive, intuitive, adaptable',3:'Expressive, educational, optimistic',4:'Energetic, practical, unconventional',5:'Versatile, communicative, quick-minded',6:'Artistic, affectionate, harmony-seeking',7:'Analytical, spiritual, introspective',8:'Disciplined, persistent, service-oriented',9:'Courageous, action-oriented, passionate'};
function reduce(n,keepMaster=false){n=Math.abs(Number(n)||0);if(keepMaster&&[11,22,33].includes(n))return n;while(n>9)n=String(n).split('').reduce((a,b)=>a+ +b,0);return n}
function digits(s){return String(s).replace(/\D/g,'').split('').map(Number)}
function nameParts(name){return String(name).toUpperCase().replace(/[^A-Z ]/g,' ').trim().split(/\s+/).filter(Boolean)}
function nameNumber(name,map){let total=0;for(const c of String(name).toUpperCase())if(map[c])total+=map[c];return {total,reduced:reduce(total)} }
function vowels(name){return String(name).toUpperCase().replace(/[^A-Z]/g,'').split('').filter(c=>'AEIOU'.includes(c)).join('')}
function consonants(name){return String(name).toUpperCase().replace(/[^A-Z]/g,'').split('').filter(c=>!('AEIOU'.includes(c))).join('')}
function letterBreakdown(name,map){return [...String(name).toUpperCase()].filter(c=>map[c]).map(c=>`${c}(${map[c]})`).join(' + ')}
function calc(dob,name){const dt=new Date(dob+'T00:00:00');const day=dt.getDate(),month=dt.getMonth()+1,year=dt.getFullYear();const birth=reduce(day), ys=digits(year).reduce((a,b)=>a+b,0), destiny=reduce(birth+month+ys);const fullC=nameNumber(name,CHAL), fullP=nameNumber(name,PYTH), soulC=nameNumber(vowels(name),CHAL), persC=nameNumber(consonants(name),CHAL), mat=reduce(destiny+fullC.reduced);const personalYear=reduce(day+month+digits(new Date().getFullYear()).reduce((a,b)=>a+b,0));return {day,month,year,birth,destiny,ys,fullC,fullP,soulC,persC,mat,personalYear,initial:name.trim().charAt(0).toUpperCase()}}
function compat(a,b){if(a===b)return ['Same number','Neutral / same vibration'];if(FAV[a]?.includes(b))return ['Favorable','The supplied framework describes this pairing as favorable.'];if(CHAL[a]?.includes(b))return ['Challenging','The supplied framework describes this pairing as challenging.'];return ['Not specified','No directional relationship was specified in the supplied framework.']}
function score(x){return x==='Favorable'?85:x==='Same number'?70:x==='Not specified'?55:30}
function loShu(dob){const counts={1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0};digits(dob).forEach(n=>{if(n)counts[n]++});return counts}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nameVariants(name,target=6){const base=name.trim(), parts=nameParts(base);const candidates=new Set([base,parts.join(' '),parts.join('')]);const suffixes=['a','h','i','y','an','en','on','in','u','e'];for(const s of suffixes){candidates.add(base+s);candidates.add(base+' '+s);if(parts.length>1)candidates.add(parts.slice(0,-1).join(' ')+' '+parts.at(-1)+s)}return [...candidates].filter(x=>/^[A-Za-z ]+$/.test(x)).slice(0,40).map(n=>({name:n,num:nameNumber(n,CHAL).reduced,score:100-Math.abs(nameNumber(n,CHAL).reduced-target)*12})).sort((a,b)=>b.score-a.score)}
window.N={PLANETS,CHALDEAN,PYTH,MEAN,reduce,nameNumber,vowels,consonants,letterBreakdown,calc,compat,score,loShu,esc,nameVariants};